const EXPERIMENTALTYPES   = {
    LIFTING_BODY: 'LIFTING_BODY',
    HYPERSONIC: 'HYPERSONIC',
    HIGH_ALTITUDE: 'HIGH_ALTITUDE',
    VERTICAL_TAKE_OFF_LANDING: 'VERTICAL_TAKE_OFF_LANDING'
};

module.exports =  {EXPERIMENTALTYPES};
